FROM python:3.12-slim

WORKDIR /app

COPY backend/requirements.txt backend/requirements-dev.txt ./
RUN pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt

EXPOSE 8000

CMD ["/app/start.sh"]
